TITLE = "Fort Knox - The Vault Nobody Has Seen"

NARRATION = """This is the most secure building on Earth. Everyone in the country knows the name. Almost nobody has ever been inside. It holds the gold of other nations. Not only the gold of America. It sits in the hills of Kentucky. A long low building made of brick. From the road it looks like a school. It is not a school at all. This is Fort Knox, Kentucky. Work began there in 1939. The building was finished in 1944. Five years of poured concrete and stone. The roof was modelled on Gothic halls. Vaulted stone arches above the corridors. Europe, rebuilt in the middle of Kentucky. The doors mattered more than the roof. The main door weighs about 56 tons. It is reportedly the heaviest vault door made. A round steel face, cropped by the frame. It swings on a solid steel hinge. Steel plate, then concrete, then more steel. The concrete runs right through the walls. The walls are thicker than the doors. A castle built to outlast a siege. The gold sits on nine floors. Rows of bars stacked to the ceiling. The reserve ran into the hundreds of billions. At its peak it weighed 12,000 tonnes. The stacks filled whole wings of it. Much of that gold belongs to other governments. Small national flags above one vault door. The vault holds their gold as well. Only a small share stays on site. Only a few hundred tonnes remain. The rest was moved out years ago. A visitor counter, a ledger, a stamp. Thousands of people tour it every year. School field trips arrive each spring. A line of children in a corridor. They walk above the stored gold. They never walk below the gold. The inner doors stay bolted shut. Almost nobody alive has seen inside."""

# One dict per intended beat, in order. The cutter assigns narration spans.
BEATS = [
    {"beat": "HOOK", "visual": "flat brick wall filling the whole frame, one gold-lit archway glowing in it; character tiny at the base, awed, looking up"},
    {"beat": "HOOK", "visual": "character close-up, flat mouth, one eyebrow line raised; speech bubble 'everyone knows it'"},
    {"beat": "HOOK", "visual": "character shrugging at a chained gate, hands turned up; speech bubble 'been inside? no.'"},
    {"beat": "IMAGE", "visual": "open vault interior, long ranks of gold bars receding to the back wall"},
    {"beat": "PIVOT", "visual": "same vault, but the bars carry many small national flags on their ends; character pointing at them"},
    {"beat": "ESTABLISH", "visual": "hand-drawn map of Kentucky, one dot marked in the north-central hills; label 'KENTUCKY'"},
    {"beat": "IMAGE", "visual": "long low brick building seen from the road, filling the full width of the frame, flat roofline"},
    {"beat": "FACT", "visual": "the same building drawn with school windows and a bell tower; character standing small at the door"},
    {"beat": "REVEAL", "visual": "the school windows and bell peel away, steel vault plates and bolts underneath; character deadpan"},
    {"beat": "TITLE", "visual": "title card, hand-lettered 'FORT KNOX' stamped across a gold bar, Kentucky outline behind it"},
    {"beat": "FACT", "visual": "old calendar page, the year 1939 circled in red pencil; shovel and trowel beside it"},
    {"beat": "FACT", "visual": "calendar page beside it, 1944 circled, a line drawn between the two dates"},
    {"beat": "IMAGE", "visual": "site under construction, concrete mixer, timber forms, workers as simple flat figures"},
    {"beat": "FACT", "visual": "roof trusses being raised over the hall, Gothic pointed arches already set below them"},
    {"beat": "IMAGE", "visual": "interior corridor, stone vaulted arches receding overhead, lamps on the floor casting flat pools"},
    {"beat": "COMPARISON", "visual": "the corridor arch drawn beside a European cathedral arch, side by side, matching shapes"},
    {"beat": "PIVOT", "visual": "character pushing on a small steel door that does not move; speech bubble 'the doors matter'"},
    {"beat": "ESCALATE", "visual": "the round vault door drawn enormous, cropped by both frame edges; character tiny at its foot"},
    {"beat": "ESCALATE", "visual": "the same door with a hand-lettered label '56 TONS' arced across it; character flattened against it"},
    {"beat": "ESCALATE", "visual": "close on the door face: concentric steel rings, a wheel handle, deep bolt holes; character awed"},
    {"beat": "IMAGE", "visual": "the hinge block alone, drawn huge, a thick steel pin running through it"},
    {"beat": "FACT", "visual": "door cross-section, layer by layer: steel plate, concrete, steel plate, each layer labelled"},
    {"beat": "ESCALATE", "visual": "cross-section of the surrounding wall, concrete a solid mass past both frame edges"},
    {"beat": "REVEAL", "visual": "the wall mass drawn taller than the door beside it, one word stamped across it: 'THICKER'"},
    {"beat": "COMPARISON", "visual": "the building drawn as a small castle with towers and an arrow slit"},
    {"beat": "PIVOT", "visual": "cutaway of the building, nine stacked floors labelled, gold on each; character climbing the levels"},
    {"beat": "ESCALATE", "visual": "gold bars stacked to the ceiling and past the top edge of the frame, rows going back"},
    {"beat": "FACT", "visual": "huge hand-lettered figure 'HUNDREDS OF BILLIONS' painted across the gold stacks"},
    {"beat": "FACT", "visual": "a scale comparison, a small car drawn under a gold bar; label 'about 1 kilo'"},
    {"beat": "ESCALATE", "visual": "the whole cutaway filled edge to edge with gold, no empty floor left showing"},
    {"beat": "FACT", "visual": "ledger page open on a desk, a long column of country names with weights beside them"},
    {"beat": "IMAGE", "visual": "small national flags in a row painted along the wall above one vault door"},
    {"beat": "PIVOT", "visual": "character nodding at the flag row; speech bubble 'not all of it is ours'"},
    {"beat": "FACT", "visual": "the full gold hall drawn, then the same hall drawn nearly bare; labels 'THEN' and 'TODAY'"},
    {"beat": "ESCALATE", "visual": "a small cluster of bars alone in the middle of a wide empty floor; character small beside them"},
    {"beat": "FACT", "visual": "an arrow leaving the building, drawn in outline, pointing off the right edge of the frame"},
    {"beat": "IMAGE", "visual": "visitor counter with a ledger, an ink stamp, a guard desk in flat fills"},
    {"beat": "FACT", "visual": "a queue of visitor figures at the counter, drawn as simple shapes, no faces"},
    {"beat": "FACT", "visual": "school bus parked outside, children as small flat figures filing toward the door"},
    {"beat": "IMAGE", "visual": "a line of children from behind in a long bright corridor, one hand on the wall"},
    {"beat": "COMPARISON", "visual": "the corridor floor drawn in cutaway, gold stacks visible right beneath their feet"},
    {"beat": "PIVOT", "visual": "the children stopped at a chained inner door; character holding a hand out, speech bubble 'not this way'"},
    {"beat": "ESCALATE", "visual": "the inner steel door shut, bolts drawn heavy across it, a red lamp above"},
    {"beat": "FINALE", "visual": "night exterior, the building almost black, one gold-lit archway; character alone in the foreground, flat mouth, speech bubble 'never seen'"},
]
