TITLE = "The Tomb of Qin Shi Huang - The Emperor They Buried With an Army"

NARRATION = """Beneath this field, eight thousand soldiers stand waiting. They are clay, and they are perfect. They stand one way for two thousand years. Their paint left them centuries after burial. They are called the Terracotta Army. Eight thousand soldiers in the dark. Six hundred horses stood beside them. They stand in long rows, in earthen pits. They are all guarding one man. His name is Qin Shi Huang. He was the first emperor of all China. In 221 BC he ended centuries of war. China had been a hundred separate kingdoms. He gave them one script and one ruler. One set of weights for every trade. That one ruler was himself. He burned every book that disagreed with him. The scholars who hid them went down too. Work started on it in 246 BC. It took decades of forced labor, unpaid. The mound above the grave copied a pyramid. They called the whole burial a heavenly palace. The whole complex lies outside Xi'an. Every single soldier is a different height. No two of the faces are the same. Then the army vanished for two thousand years. In 1974 farmers were digging a well. A shovel struck something hard in the dirt. It was a clay shoulder, then a face. The clay broke when the diggers raised it. So the hole was covered over and abandoned. In 2012 a new pit was opened. More than a thousand soldiers lay inside. Two bronze cranes lay broken in the dirt. Archaeologists repaired them with modern glue anyway. In 1983 a scientist poured acid on figures. Nobody can read those markings ever again. Soil samples from the mound gave up mercury. Enough of it to fill a small pool. The old records say rivers of liquid mercury. Mercury is a slow poison. The body never really lets it go. The main chamber has never been opened once. It lies under the mound, still sealed. Behind the army, the door stays shut."""

# One dict per intended beat, in order. The cutter assigns narration spans.
BEATS = [
 {"beat": "HOOK", "visual": "wide empty flat brown dirt field outside Xi'an, low horizon, nothing on screen; hand-lettered label 'OUTSIDE XI'AN, CHINA'"},
 {"beat": "HOOK", "visual": "cut into the soil: a clay soldier standing upright, undisturbed, dust on its shoulders"},
 {"beat": "IMAGE", "visual": "the same clay figure held, full frame, cropped at both side edges"},
 {"beat": "IMAGE", "visual": "close on the figure's shoulder and face, paint flaking away in flakes on the dirt"},
 {"beat": "TITLE", "visual": "hand-lettered 'TERRACOTTA ARMY' stamped across the top of a rank of clay figures"},
 {"beat": "FACT", "visual": "a dark earthen pit in cross-section, rows of clay figures standing shoulder to shoulder below ground"},
 {"beat": "FACT", "visual": "two clay horses, harnessed, filling the frame, cropped at the left edge"},
 {"beat": "FACT", "visual": "long ranks of warriors receding into the dark of the pit, the rows continuing past the frame"},
 {"beat": "REVEAL", "visual": "all the clay faces turned the same direction; the character standing among them, small"},
 {"beat": "REVEAL", "visual": "name stamp 'QIN SHI HUANG'; character below it, pointing up at the stamp"},
 {"beat": "ESTABLISH", "visual": "character full body before a plain map of China; speech bubble 'first emperor'"},
 {"beat": "FACT", "visual": "calendar page marked '221 BC'; crossed arrows and broken banners on the map"},
 {"beat": "FACT", "visual": "map covered in many small red kingdom shapes with fighting arrows between them"},
 {"beat": "PIVOT", "visual": "the red shapes merging into one outline; one road, one script sheet, one crown"},
 {"beat": "FACT", "visual": "a set of bronze weights of different shapes, all stamped with one mark"},
 {"beat": "REVEAL", "visual": "a single figure on a throne, arms folded; character below, deadpan; speech bubble 'himself'"},
 {"beat": "ESCALATE", "visual": "a stack of old books going into a fire, hand-drawn flames"},
 {"beat": "ESCALATE", "visual": "a robed scholar figure lowered into a pit; character recoiling from the edge"},
 {"beat": "FACT", "visual": "plan of the tomb complex drawn on a wall; one square block marked '246 BC'"},
 {"beat": "IMAGE", "visual": "long lines of laborers hauling earth, drawn small and repeating to the horizon"},
 {"beat": "COMPARISON", "visual": "the earth mound drawn beside a small stepped pyramid silhouette; label 'pyramid'"},
 {"beat": "REVEAL", "visual": "the mound sketched as a celestial palace: stars, a moon disc, cloud bands"},
 {"beat": "ESTABLISH", "visual": "a simple hand-drawn map plan with a dot east of a walled city; label 'OUTSIDE XI'AN'"},
 {"beat": "FACT", "visual": "three clay soldiers side by side, heights visibly different; a measuring stick behind them"},
 {"beat": "FACT", "visual": "two clay faces side by side, clearly different; label 'no two the same'"},
 {"beat": "PIVOT", "visual": "the empty field again, quiet; character small at the edge of frame"},
 {"beat": "HOOK", "visual": "1974; two farmers swinging pickaxes beside a half-dug well"},
 {"beat": "FACT", "visual": "shovel blade striking something hard, clay chipping off the edge"},
 {"beat": "REVEAL", "visual": "a clay shoulder and a clay face emerging from the dirt, loose soil falling"},
 {"beat": "FACT", "visual": "hands lifting a broken clay arm, fragments dropping back into the pit"},
 {"beat": "PIVOT", "visual": "the pit filled in, covered with a tarp and a small building over it"},
 {"beat": "REVEAL", "visual": "plan view of an L-shaped corridor of vaults; label 'PIT 1, 2012'"},
 {"beat": "FACT", "visual": "the L-shaped pit filled with clay figures, seen from above, cropped at both edges"},
 {"beat": "ESCALATE", "visual": "two bronze crane figures lying in fragments on the dirt, both broken"},
 {"beat": "FACT", "visual": "a modern glue brush and epoxy bottle drawn next to a repaired crane body"},
 {"beat": "ESCALATE", "visual": "a figure pouring acid from a jar onto terracotta armor; surface dissolving"},
 {"beat": "FACT", "visual": "the same armor plate greyed out, its painted surface gone; character looking away"},
 {"beat": "REVEAL", "visual": "a soil sample jar in a lab tray; a bright silver bead forming inside"},
 {"beat": "ESCALATE", "visual": "a low tunnel with a shallow pool of liquid mercury reflecting the lamp"},
 {"beat": "FACT", "visual": "an old scroll unrolling; painted on it: two winding silver rivers around a shape"},
 {"beat": "FACT", "visual": "a silver droplet on a fingertip; character wiping his mouth; label 'poison'"},
 {"beat": "IMAGE", "visual": "a body outline with the silver still lodged in it, drawn flat"},
 {"beat": "FINALE", "visual": "a heavy stone door in the dark, shut; one flat painted guard figure beside it"},
 {"beat": "FINALE", "visual": "the sealed mound in cross-section: outer pits, then solid earth, then a black sealed void"},
 {"beat": "FINALE", "visual": "wide dark cutaway: outer clay ranks cropped at the frame edge, the sealed chamber a black void beyond them; character very small, awed"},
]