TITLE = "Vatican Archives - The Room With No Windows"

NARRATION = """Beneath Vatican City there is an archive. The rooms down there have no windows. The place is called the Vatican Archives. The archive doors opened in 1939. They opened once, for outside scholars. Then the doors closed again, quietly. The rooms run deep under the hill. The shelves stretch out for kilometres. A wooden ladder slides along a rail. No electric light is allowed down there. Every window was walled up on purpose. Nobody may photograph a single page. Not even a phone screen is allowed. A camera flash would harm the paper. Some of that paper cannot be opened. The old pages have fused together. Open them and the paper tears. So most of those boxes stay shut. Some documents are never consulted again. They were catalogued once, then shelved. A single index card, one line on it. That one line is the whole record. Fragile pages are filmed instead of opened. Other pages stay closed for ever. A microfilm reel beside a sealed box. The shelving system itself is kept quiet. Few people know how the stacks run. The actual plan is filed elsewhere, upstairs. Nobody has ever carried it down. A reader lost between two tall shelves. The Vatican has shelved many older records. Some have stayed shut for years. Others open for a chosen few only. Access is a favour, not a right. A hand holding out a small key. The stacks hold centuries nobody has read. Nobody knows what is on the lowest shelves. The dark down there is absolute."""

# One dict per intended beat, in order. The cutter assigns narration spans.
BEATS = [
    {"beat": "HOOK", "visual": "cross-section of a hill under Vatican City, one dark chamber cut into the rock, filling the frame"},
    {"beat": "HOOK", "visual": "close on a windowless stone wall, bricks filled in where glass would be"},
    {"beat": "TITLE", "visual": "hand-lettered 'THE VATICAN ARCHIVES' stamped tall across the archive door"},
    {"beat": "FACT", "visual": "old calendar page with the year 1939 ringed in red pencil"},
    {"beat": "FACT", "visual": "a small group of scholars at a plain wooden table, no ornament"},
    {"beat": "PIVOT", "visual": "the same heavy door shut again, character standing deadpan before it"},
    {"beat": "ESTABLISH", "visual": "cutaway of stacked chambers descending under the hill, each one deeper than the last"},
    {"beat": "IMAGE", "visual": "one endless shelf run filling the frame edge to edge, receding to no end"},
    {"beat": "IMAGE", "visual": "wooden rolling ladder hooked onto a shelf rail, close"},
    {"beat": "FACT", "visual": "bare bulb behind a wire cage, switched off; label 'NO ELECTRIC LIGHT'"},
    {"beat": "ESTABLISH", "visual": "mason's blocked-up window arch, fresh brick inside an old stone frame"},
    {"beat": "PIVOT", "visual": "a hand holding a camera below a page, red slash across it; character shrugging"},
    {"beat": "ESCALATE", "visual": "phone screen glowing flat on a cradle beside a parchment sheet"},
    {"beat": "COMPARISON", "visual": "camera flash burst drawn as a white star over brittle brown paper"},
    {"beat": "FACT", "visual": "an open box of fused pages, edges welded in a single pale block"},
    {"beat": "ESCALATE", "visual": "close on two pages stuck face to face, a torn corner hanging loose"},
    {"beat": "ESCALATE", "visual": "a page being lifted and splitting, jagged tear line in red"},
    {"beat": "REVEAL", "visual": "lid lowered on a wooden box, hands flat on the shut top"},
    {"beat": "PIVOT", "visual": "character reaching for a box, then stopping; speech bubble 'not this one'"},
    {"beat": "FACT", "visual": "an old catalogue page with one single line of handwriting, the rest blank"},
    {"beat": "IMAGE", "visual": "one index card in a card tray, most of the tray empty around it"},
    {"beat": "REVEAL", "visual": "magnifier over that one line of writing, character awed"},
    {"beat": "FACT", "visual": "a reel-to-reel microfilm machine, a page flattened under the lens"},
    {"beat": "ESCALATE", "visual": "a sealed box on a shelf stamped with a red 'CLOSED' band"},
    {"beat": "COMPARISON", "visual": "microfilm reel on the left, sealed box on the right, drawn to the same size"},
    {"beat": "PIVOT", "visual": "a diagram of the whole stack layout, half covered by a hand"},
    {"beat": "REVEAL", "visual": "character squinting at a shelf-end placard, shoulders hunched"},
    {"beat": "FACT", "visual": "a plan rolled up and locked in an upstairs drawer, labelled in a different hand"},
    {"beat": "ESCALATE", "visual": "an empty hand leaving the stairs, no plan in it; floor line drawn as a threshold"},
    {"beat": "IMAGE", "visual": "character small, seen from above, wedged between two towering shelf faces"},
    {"beat": "FACT", "visual": "shelf row with a wide dark gap where bound volumes should sit"},
    {"beat": "ESCALATE", "visual": "a wall calendar with a decade of pages unturned, thick and swollen"},
    {"beat": "FACT", "visual": "one box drawn out on a table under a lamp, three people standing at a respectful distance"},
    {"beat": "PIVOT", "visual": "a hand held out flat, palm up; character looking away from it"},
    {"beat": "IMAGE", "visual": "one small key resting in an open palm, flat fills, plain background"},
    {"beat": "FINALE", "visual": "vast shelf run again, this time packed with unlabelled boxes, none of them open"},
    {"beat": "FINALE", "visual": "character at the bottom of a shelf, looking down; speech bubble 'nobody knows'"},
    {"beat": "FINALE", "visual": "the lowest shelf in near-total black, only the character awed at the edge of the dark"},
]
