TITLE = "Room 39 - The Sealed Bunker Under The Kremlin"

NARRATION = """Under the Kremlin, a nuclear bunker waits. Nobody has ever walked through its door. Its code name is Object 739. Stalin ordered it built in the 1950s. He wanted one refuge of his own. It sits below a small park. Moscow itself was built on sinking ground. Everything above the ceiling is hardened steel. Ordinary buildings nearby rest on thin foundations. The doors were made to close forever. Each leaf weighs hundreds of tonnes. They are sealed, and never opened. One closed door, filling the whole frame. Stalin reportedly never went inside. The corridors were lined with lead. Floor to ceiling, plate over plate. Below that, a control room waits. The room is said to hold one console. A console drawn small, in the dark. One row of switches, one big button. No official record confirms the console. Other bunkers from that era were documented. This one has never been filmed inside. Satellite images show only the surface. The entrance sits behind an ordinary fence. An ordinary fence on an ordinary street. It ends at a set of steel doors. Rumour says they open on a code. No code has ever been published. The whole site is a system. A line of sensors ringing the block. Something out there is still listening. The system may have outlived its builder. Under the park, a red light waits. Russia has never confirmed what remains. No one has gone down in decades. The door is still shut, and still waiting."""

# One dict per intended beat, in order. The cutter assigns narration spans.
BEATS = [
    {"beat": "HOOK", "visual": "cross-section of a city block under a park, one deep chamber cut into the clay; label 'BENEATH THE KREMLIN'"},
    {"beat": "HOOK", "visual": "a single steel door in flat grey concrete, never opened; character small in front of it, looking up"},
    {"beat": "TITLE", "visual": "hand-lettered 'OBJECT 739' stamped across a blueprint of the bunker"},
    {"beat": "ESTABLISH", "visual": "plain black-and-white portrait sketch of Stalin, no shading, label '1950s'"},
    {"beat": "FACT", "visual": "one man alone at a desk, drawing a plan by hand"},
    {"beat": "IMAGE", "visual": "flat green park above, grey chamber below, the two separated by a thick line"},
    {"beat": "FACT", "visual": "cross-section of Moscow soil: soft clay layers, water pooling at the bottom"},
    {"beat": "FACT", "visual": "armoured ceiling slab, riveted, drawn very thick; character standing on it for scale"},
    {"beat": "COMPARISON", "visual": "a thin ordinary basement wall beside it, hand-lettered label 'ABOVE' vs 'BELOW'"},
    {"beat": "ESCALATE", "visual": "close on a huge blast door leaf filling the frame, wheel lock in the middle"},
    {"beat": "FACT", "visual": "the same door with a small figure of a truck beside it, for scale; label 'HUNDREDS OF TONNES'"},
    {"beat": "ESCALATE", "visual": "weld seam drawn across the door edge, bright and uneven, sealing it shut"},
    {"beat": "IMAGE", "visual": "the closed door held dead centre, filling the whole frame, nothing else in shot"},
    {"beat": "PIVOT", "visual": "character shrugging at a desk; speech bubble 'he never went in'"},
    {"beat": "FACT", "visual": "cutaway corridor cross-section, thick dark plates on floor, walls and ceiling"},
    {"beat": "FACT", "visual": "the plates drawn edge to edge, one long continuous band; label 'LEAD LINED'"},
    {"beat": "REVEAL", "visual": "one low chamber at the end of the corridor, single light above it; character tiny, awed"},
    {"beat": "ESCALATE", "visual": "cutaway of the chamber, a blocky console shape under a hanging lamp; label 'SAID TO EXIST'"},
    {"beat": "IMAGE", "visual": "the console alone in a wide dark room, one small warm pool of light"},
    {"beat": "ESCALATE", "visual": "close on one row of switches and one large red button under a hinged cover"},
    {"beat": "PIVOT", "visual": "character deadpan beside an empty file folder; speech bubble 'no record'"},
    {"beat": "COMPARISON", "visual": "another bunker from the same decade, open to visitors, a queue of small figures"},
    {"beat": "COMPARISON", "visual": "our bunker door beside it, the visitor line cut off at the edge"},
    {"beat": "ESCALATE", "visual": "satellite passing overhead looking straight down; only rooftops and trees visible"},
    {"beat": "FACT", "visual": "ordinary grey perimeter fence on an ordinary street, parked cars behind it"},
    {"beat": "IMAGE", "visual": "the same fence held from further back, trees, a bench, a bus stop"},
    {"beat": "REVEAL", "visual": "the fence line running to a plain steel door set into a brick wall; label 'ENTRANCE'"},
    {"beat": "ESCALATE", "visual": "a keypad and a small camera on a stalk above the steel door"},
    {"beat": "FACT", "visual": "the keypad close, no numbers legible, a blank panel of twelve unmarked buttons"},
    {"beat": "ESTABLISH", "visual": "the whole block drawn as a system: fence, sensors, door, chamber, all linked by one dashed line"},
    {"beat": "IMAGE", "visual": "a ring of small sensor boxes around the block, each with a short antenna"},
    {"beat": "FACT", "visual": "one sensor box close, a small red lamp lit on its face"},
    {"beat": "ESCALATE", "visual": "the block's outline dissolving into rust and weeds; the dashed line still runs through it"},
    {"beat": "IMAGE", "visual": "the park at night, cutaway, a small red glow in the chamber below; no label"},
    {"beat": "FACT", "visual": "an official document on a desk, the relevant line left blank and unmarked"},
    {"beat": "FACT", "visual": "the chamber dark, an empty helmet on a chair, nothing moving"},
    {"beat": "FINALE", "visual": "the steel door held in near-darkness, a red lamp beside it; character small, seen from behind, waiting; no label"},
]
